import React from 'react';
import { Link } from 'react-router-dom';

export const TermsPage: React.FC = () => {
  return (
    <div style={{ backgroundColor: 'var(--bg-0)', minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      {/* Header */}
      <header
        style={{
          height: '52px',
          borderBottom: '1px solid var(--line)',
          backgroundColor: 'var(--bg-1)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '0 32px',
        }}
      >
        <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <span style={{ width: '10px', height: '10px', backgroundColor: 'var(--accent)', display: 'inline-block' }} />
          <span className="font-display" style={{ fontSize: '16px' }}>SignSight</span>
        </Link>
        <Link to="/auth" className="btn btn-primary" style={{ height: '28px', fontSize: '11px' }}>
          Console Sign In
        </Link>
      </header>

      {/* Main Grid with Sticky TOC on left */}
      <div
        style={{
          maxWidth: '1080px',
          margin: '40px auto',
          padding: '0 24px',
          display: 'grid',
          gridTemplateColumns: '220px minmax(320px, 68ch)',
          gap: '48px',
          alignItems: 'start',
          flex: 1,
          width: '100%',
        }}
      >
        {/* Sticky TOC on Left */}
        <aside style={{ position: 'sticky', top: '72px' }}>
          <div className="label-caps" style={{ marginBottom: '12px' }}>Table of Contents</div>
          <nav style={{ display: 'flex', flexDirection: 'column', gap: '8px', fontSize: '12px' }}>
            <a href="#acceptance" style={{ color: 'var(--text-dim)' }}>1. Acceptance of Terms</a>
            <a href="#authorized-use" style={{ color: 'var(--text-dim)' }}>2. Authorized Telemetry Only</a>
            <a href="#advisory-nature" style={{ color: 'var(--text-dim)' }}>3. Advisory-Only Detections</a>
            <a href="#accountability" style={{ color: 'var(--text-dim)' }}>4. Account Accountability</a>
            <a href="#limitation" style={{ color: 'var(--text-dim)' }}>5. Limitation of Liability</a>
            <a href="#prototype-notice" style={{ color: 'var(--text-dim)' }}>6. Prototype Disclaimer</a>
          </nav>
        </aside>

        {/* Longform Text (68ch) */}
        <main>
          <Link
            to="/"
            style={{ fontSize: '12px', color: 'var(--text-dim)', marginBottom: '16px', display: 'inline-block' }}
          >
            &larr; Back to Overview
          </Link>

          <h1 className="font-display" style={{ fontSize: '32px', marginBottom: '8px' }}>
            Terms &amp; Conditions
          </h1>
          <div className="font-mono label-caps" style={{ color: 'var(--text-faint)', marginBottom: '32px' }}>
            LAST UPDATED: OCTOBER 2, 2026 &bull; PROTOTYPE DOCUMENT
          </div>

          <section id="acceptance" style={{ marginBottom: '32px' }}>
            <h2 className="font-display" style={{ fontSize: '18px', marginBottom: '8px' }}>
              1. Acceptance of Terms
            </h2>
            <p style={{ color: 'var(--text)', lineHeight: 1.6, fontSize: '14px' }}>
              By accessing the SignSight web console or invoking its telemetry ingestion endpoints, you agree to comply with these Terms of Service. These conditions govern usage of the software created for Microsoft Innovate 2026.
            </p>
          </section>

          <section id="authorized-use" style={{ marginBottom: '32px' }}>
            <h2 className="font-display" style={{ fontSize: '18px', marginBottom: '8px' }}>
              2. Authorized Telemetry Only
            </h2>
            <p style={{ color: 'var(--text)', lineHeight: 1.6, fontSize: '14px' }}>
              You may submit network traffic captures and flow records solely from systems, testbeds, and network segments that you own or have explicit administrative authorisation to monitor. Capturing or evaluating third-party traffic without consent is strictly prohibited.
            </p>
          </section>

          <section id="advisory-nature" style={{ marginBottom: '32px' }}>
            <h2 className="font-display" style={{ fontSize: '18px', marginBottom: '8px' }}>
              3. Advisory-Only Detections (Model Output Disclaimer)
            </h2>
            <p style={{ color: 'var(--text)', lineHeight: 1.6, fontSize: '14px', marginBottom: '12px' }}>
              SignSight outputs are generated by statistical and machine learning algorithms (Isolation Forest and LightGBM). Detections, severity ratings, and class attributions are advisory indicators intended to guide human analysts.
            </p>
            <p style={{ color: 'var(--text)', lineHeight: 1.6, fontSize: '14px' }}>
              Machine learning models may produce false positives or false negatives. SignSight should not be deployed as an autonomous, unmonitored blocking gateway for critical infrastructure without qualified human review.
            </p>
          </section>

          <section id="accountability" style={{ marginBottom: '32px' }}>
            <h2 className="font-display" style={{ fontSize: '18px', marginBottom: '8px' }}>
              4. Account Accountability
            </h2>
            <p style={{ color: 'var(--text)', lineHeight: 1.6, fontSize: '14px' }}>
              Analysts and administrators are responsible for all actions recorded under their credentials in the system audit log, including model deployments, rollback triggers, and verdict classifications.
            </p>
          </section>

          <section id="limitation" style={{ marginBottom: '32px' }}>
            <h2 className="font-display" style={{ fontSize: '18px', marginBottom: '8px' }}>
              5. Limitation of Liability
            </h2>
            <p style={{ color: 'var(--text)', lineHeight: 1.6, fontSize: '14px' }}>
              The software is provided &ldquo;as is&rdquo;, without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose, or non-infringement.
            </p>
          </section>

          <section id="prototype-notice" style={{ marginBottom: '48px' }}>
            <div className="panel" style={{ padding: '16px', borderLeft: '3px solid var(--accent)' }}>
              <div className="label-caps" style={{ color: 'var(--accent)', marginBottom: '4px' }}>
                Legal Notice
              </div>
              <p style={{ fontSize: '12px', color: 'var(--text-dim)', lineHeight: 1.5 }}>
                Prototype document, not legal advice. SignSight is an academic prototype constructed for competitive demonstration at Microsoft Innovate 2026.
              </p>
            </div>
          </section>
        </main>
      </div>
    </div>
  );
};
