# Generated by Django 5.1.15 on 2026-10-01 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('model_type', models.CharField(max_length=100)),
                ('artifact_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField()),
                ('deployed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
