# Generated by Django 5.1.15 on 2026-10-01 06:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField()),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('alert_type', models.CharField(choices=[('known_attack', 'Known Attack'), ('novel_suspicious', 'Novel Suspicious'), ('uncertain_normal', 'Uncertain Normal')], default='known_attack', max_length=50)),
                ('explanation', models.JSONField(blank=True, null=True)),
                ('top_features', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('true_positive', 'True Positive'), ('false_positive', 'False Positive')], max_length=20, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dest_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('traffic_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.trafficrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AlertThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
