# Generated by Django 5.1.15 on 2026-10-01 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_features', models.JSONField(default=dict)),
                ('protocol_type', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('flag', models.CharField(blank=True, max_length=20, null=True)),
                ('src_bytes', models.BigIntegerField(blank=True, null=True)),
                ('dst_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=50)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dest_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
